query allPosts($subforumUrl: String!) {
  allPosts(
    filter: { subforum: { url: $subforumUrl } }
    orderBy: voteCount_DESC
  ) {
    id
    title
    voteCount
    subforum {
      name
    }
  }
}
